# Generated by Django 4.2.5 on 2023-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_answer_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
